CREATE TABLE IF NOT EXISTS Users(
 id SERIAL PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(225) NOT NULL,
 email VARCHAR(100) NOT NULL UNIQUE,
 role VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS Products (
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(225) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
role VARCHAR(10) NOT NULL
);